#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.

psCommand=".\\Tools\\GitHooks\\post-commit.ps1"
c:/windows/system32/WindowsPowerShell/v1.0/PowerShell.exe -Sta -ExecutionPolicy RemoteSigned -NoProfile -Command "$psCommand"