#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.

psCommand=".\\Tools\\GitHooks\\post-commit.ps1"
PowerShell.exe -Sta -ExecutionPolicy RemoteSigned -Command "$psCommand"