#!/bin/sh
#
# Copyright (c) 2006, 2008 Junio C Hamano
#
# The "pre-rebase" hook is run just before "git rebase" starts doing
# its job, and can prevent the command from running by exiting with
# non-zero status.
#
# The hook is called with the following parameters:
#
# $1 -- the upstream the series was forked from.
# $2 -- the branch being rebased (or empty when rebasing the current branch).

newBaseCommit=$1
rebasingBranchName=$2
psCommand=".\\Tools\\GitHooks\\pre-rebase.ps1 -NewBaseCommit \"$newBaseCommit\" -RebasingBranchName \"$rebasingBranchName\""
PowerShell.exe -Sta -ExecutionPolicy RemoteSigned -Command "$psCommand"
